[build]
target = "./index.html"

[watch]
# Ignore these files/folders when watching for frontend rebuild.
ignore = [
    "backend/",
    ".github/",
    ".vscode/",
    "scss-input/",
    ".gitignore",
    "LICENSE.txt",
    "README.md",
    "rustfmt.toml",
    ".taurignore",
    "Trunk.toml",
]

[serve]
address = "127.0.0.1"
port = 1420
open = false
