[package]
name = "chipbox-glue"
version = "0.0.0"
edition = "2021"

[dependencies]
# common
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
# backend
chipbox-backend-lib = { path = "../backend-lib" }
tauri = { version = "1.4", optional = true }
tokio = { version = "1.29", features = ["macros", "time"], optional = true }
# frontend
yew = { version = "0.20", optional = true }
wasm-bindgen = { version = "0.2", features = [
    "serde-serialize",
], optional = true }
serde-wasm-bindgen = { version = "0.5", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
web-sys = { version = "0.3", optional = true }
js-sys = { version = "0.3", optional = true }
wasm-timer = "0.2.5"

[features]
backend = ["dep:tauri", "chipbox-backend-lib/backend", "dep:tokio"]
frontend = [
    "dep:yew",
    "dep:serde-wasm-bindgen",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "dep:web-sys",
    "dep:js-sys",
]
