[package]
name = "chipbox-glue"
version = "0.0.0"
edition = "2021"

[features]
backend = [
    # workspace deps
    "dep:chipbox-backend",
    # deps
    "dep:tauri",
    "dep:tokio",
]
frontend = [
    # deps
    "dep:yew",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "dep:wasm-timer",
    "dep:serde-wasm-bindgen",
    "dep:js-sys",
]

[dependencies]
## backend only deps
# workspace deps
chipbox-backend = { path = "../backend", optional = true }
# deps
tauri = { version = "1.4", optional = true }
tokio = { version = "1.29", features = [
    "macros",
    "fs",
    "tracing",
    "time",
], optional = true }

## fronted only deps
# deps
yew = { version = "0.21", optional = true }
wasm-bindgen = { version = "0.2", features = [
    "serde-serialize",
], optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
wasm-timer = { version = "0.2", optional = true }
serde-wasm-bindgen = { version = "0.6.1", optional = true }
js-sys = { version = "0.3", optional = true }
tracing = "0.1.40"

## common deps
# workspace deps
chipbox-common = { path = "../common" }
# deps
serde = { version = "1.0", features = ["derive", "rc"] }
