[package]
name = "chipbox-ui-panel"
version = "0.1.0"
edition = "2021"

[dependencies]
## tracing
tracing = { workspace = true }
## wasm frontend
yew = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
gloo = { workspace = true }
