use std::path::Path;

use miette::{Context as _, IntoDiagnostic as _};

fn main() -> miette::Result<()> {
    let export = specta::export().register::<chipbox_scene::Scene>();
    let export_dir = Path::new(env!("TS_EXPORT_DIR")).join("scene.ts");
    specta_typescript::Typescript::new()
        .bigint(specta_typescript::BigIntExportBehavior::Number)
        //.with_serde()
        .framework_header("//! Generated by/from chipbox-scene.")
        .export_to(export_dir, &export)
        .into_diagnostic()
        .wrap_err("export to typescript")?;
    Ok(())
}
