[package]
name = "chipbox-common"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
once_cell = { workspace = true }
cssparser = { workspace = true }
derive_more = { workspace = true }
cssparser-color = { workspace = true }
