# Adapted from the example at https://github.com/actions-rs/clippy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "38 14 * * 2"
name: rust-clippy
jobs:
  rust-clippy:
    name: Run rust-clippy analyzis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      # Note that there is no release tag available yet
      # and the following code will use master branch HEAD
      # all the time.
      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets
